const ARCHIVE3 = [
{
id: "bohemian-cremation",
title: "Bohemian Grove – Cremation of Care (Footage)",
years: "1880s–present (filmed 2000)",
yearStart: 2000,
countries: ["USA"],
agencies: ["Bohemian Club"],
category: "Elite network / documented ritual",
status: "Proven gathering + ritual — criminal claims unproven",
summary: "Private all-male retreat; mock-sacrifice play filmed by infiltrators in 2000.",
details: "Proven: 2,700-acre Monte Rio camp, members included Reagan, Nixon, Roosevelt; 40ft owl shrine; Cremation of Care play performed yearly. Footage: Alex Jones/Mike Hanson 2000 hidden-camera video (grainy, publicly sold), Jon Ronson Channel 4 2000s, NYT/Annie Leibovitz stills. Sonoma County records and member memoirs confirm ritual as theater. Alleged human sacrifice has no bodies, police reports or credible witnesses — labeled unproven.",
sources: "Jones 2000 tape; Ronson Secret Rulers; club histories; Nixon tapes on Grove"
},
{
id: "bohemian-manhattan",
title: "Bohemian Grove – Manhattan Project Planning",
years: "1942–1945",
yearStart: 1942,
countries: ["USA"],
agencies: ["Bohemian Club", "OSRD"],
category: "Elite network / weapons planning",
status: "Proven — histories",
summary: "Key atomic-bomb planning meetings held at Grove in 1942.",
details: "Proven via Oppenheimer/Teller biographies and DOE histories: September 1942 meeting set Berkeley lab role. Photos of scientists at Grove exist in archives. No secret footage, but documents stronger than ritual tape. Shows Grove as real policy venue, separate from sacrifice lore.",
sources: "DOE Manhattan histories; Bird/Sherwin Oppenheimer"
},
{
id: "bilderberg-meetings",
title: "Bilderberg Meetings (Footage/Lists)",
years: "1954–present",
yearStart: 1954,
countries: ["Netherlands", "USA", "UK", "Others"],
agencies: ["Bilderberg Group"],
category: "Elite network / policy forum",
status: "Proven meetings — control claims unproven",
summary: "Annual 120-person off-record talks; protest/drone footage yearly, official lists since 2010s.",
details: "Proven: Hotel De Bilderberg 1954, Prince Bernhard/CIA links; attendee lists, press releases and Chatham House rule confirmed. Footage: perimeter protests, arrivals, 2010s YouTube livestreams. No minutes released, fueling control theories, but no credible document proves world-government orders. List as proven forum, unproven master-plot.",
sources: "Bilderberg official archive; police/protest footage; Hatch/Ervine histories"
},
{
id: "skull-bones",
title: "Skull and Bones – Yale (Photos)",
years: "1832–present",
yearStart: 1832,
countries: ["USA"],
agencies: ["Yale society"],
category: "Elite network / society",
status: "Proven society — ritual footage scarce",
summary: "Yale senior society; Bush Sr/Jr and Kerry admitted membership 2004.",
details: "Proven: Russell Trust, tomb building photos, member rosters leaked. Ritual claims rest on 2000s night-vision clips of mock threats (authenticity debated) and secondhand accounts. No credible criminal footage. Include as proven network, weak footage record.",
sources: "Robbins Secrets of the Tomb; 2004 Meet the Press admissions"
},
{
id: "epstein-island-docs",
title: "Epstein Island / Flight Logs (Documents, No Ritual Footage)",
years: "1998–2019",
yearStart: 1998,
countries: ["USA", "US Virgin Islands"],
agencies: ["Epstein network"],
category: "Elite network / crimes proven",
status: "Crimes proven — sacrifice/tape claims unproven",
summary: "Flight logs, photos and 2019 raids prove trafficking network; no credible elite-ritual footage.",
details: "Proven: 2008 Florida conviction, 2019 SDNY trafficking indictment, pilot logs naming Clinton, Trump, Prince Andrew and others as passengers (attendance ≠ crime), island aerials and FBI house footage. Giuffre photos with Andrew settled 2022. Claims of underground temple sacrifices or mass blackmail tapes have no released video or court exhibit — labeled unproven. Do not cite attendance as guilt.",
sources: "SDNY indictments; flight-log releases; FBI search inventory"
},
{
id: "davos-wef",
title: "WEF Davos (Fully Public Footage)",
years: "1971–present",
yearStart: 1971,
countries: ["Switzerland", "Global"],
agencies: ["World Economic Forum"],
category: "Elite network / public forum (contrast)",
status: "Proven — fully filmed",
summary: "Yearly elite forum with thousands of hours of open video — control case.",
details: "Every panel livestreamed, transcripts online. Useful contrast: proves elites do meet openly; secrecy varies by forum. No need for infiltration theories where cameras are invited. Included to calibrate evidence bar.",
sources: "WEF public archive"
},
{
id: "cercle-pinay",
title: "Le Cercle / Pinay Circle (No Public Footage)",
years: "1950s–present",
yearStart: 1953,
countries: ["France", "UK", "USA", "Germany"],
agencies: ["Intelligence-linked group"],
category: "Elite network / intelligence",
status: "Proven via papers — no ritual footage",
summary: "Conservative intel-linked talks (Antoine Pinay, Strauss, Casey); attendance proven by papers.",
details: "Proven via Langemann papers (1982 leak) and press investigations. No public video; secrecy is agenda, not ritual. Alleged election manipulation unproven beyond attendance. Strongest intel-elite paper trail after Bilderberg.",
sources: "Langemann papers; Guardian/Spiegel investigations"
},
{
id: "p2-lodge",
title: "Propaganda Due P2 Lodge (Seized Lists)",
years: "1970s–1981",
yearStart: 1976,
countries: ["Italy"],
agencies: ["P2", "SISMI"],
category: "Elite network / corruption proven",
status: "Proven — court findings",
summary: "Secret lodge of 1,000+ elites (Berlusconi, generals, bankers); 1981 raid seized lists.",
details: "Led by Licio Gelli. Parliamentary Anselmi Commission proved subversive network tied to Banco Ambrosiano collapse and Bologna context. No ritual-sacrifice footage; crime is financial/political, documented in court. Best-documented criminal elite lodge.",
sources: "Anselmi Commission; court verdicts"
},
{
id: "nixon-grove-tapes",
title: "Nixon Tapes on Bohemian Grove (Audio)",
years: "1971",
yearStart: 1971,
countries: ["USA"],
agencies: ["White House"],
category: "Elite audio / primary source",
status: "Proven — NARA audio",
summary: "Nixon calls Grove 'faggy' and limits attendance — proves insider view.",
details: "13 May 1971 White House tapes (NARA): Nixon and Haldeman discuss homosexual connotations and membership. Publicly released, transcribed. No crime discussed. Strongest primary audio that Grove is elite social, not command center in this record.",
sources: "Nixon tapes, NARA release"
}
];
