const ARCHIVE = [
{
id: "mkultra",
title: "MKUltra",
years: "1953–1973",
yearStart: 1953,
countries: ["USA"],
agencies: ["CIA"],
category: "Mind control / human experiment",
status: "Proven — declassified",
summary: "CIA program researching mind control via LSD, hypnosis, sensory deprivation and interrogation techniques, often on unwitting subjects.",
details: "Authorized in 1953 and exposed by the Church Committee and 1977 Senate hearings. Most records were destroyed in 1973. Encompassed 149 subprojects at universities, prisons and hospitals.",
sources: "Church Committee (1975-76); Senate MKUltra hearings (1977)"
},
{
id: "midnight-climax",
title: "Operation Midnight Climax",
years: "1954–1964",
yearStart: 1954,
countries: ["USA"],
agencies: ["CIA"],
category: "Mind control / human experiment",
status: "Proven — declassified",
summary: "MKUltra subproject using safehouses in San Francisco and New York to dose unwitting men with LSD and observe effects.",
details: "Run by Sidney Gottlieb and George Hunter White. Used prostitutes to lure subjects. Revealed in Church Committee investigations.",
sources: "Church Committee; CIA Inspector General histories"
},
{
id: "artichoke",
title: "Project ARTICHOKE",
years: "1951–1953",
yearStart: 1951,
countries: ["USA"],
agencies: ["CIA"],
category: "Mind control / interrogation",
status: "Proven — declassified",
summary: "Predecessor to MKUltra focused on interrogation drugs, hypnosis and whether individuals could be forced to assassinate.",
details: "Evolved from Project BLUEBIRD. Tested morphine, mescaline, LSD and hypnosis on prisoners and agents.",
sources: "CIA declassified ARTICHOKE memoranda"
},
{
id: "bluebird",
title: "Project BLUEBIRD",
years: "1950–1951",
yearStart: 1950,
countries: ["USA"],
agencies: ["CIA"],
category: "Mind control / interrogation",
status: "Proven — declassified",
summary: "Early CIA mind-control program to study conditioning, interrogation drugs and defense against Soviet techniques.",
details: "Renamed ARTICHOKE in 1951. Authorized use of unwitting subjects in some tests according to declassified memos.",
sources: "CIA BLUEBIRD/ARTICHOKE declassifications"
},
{
id: "mknaomi",
title: "Project MKNAOMI",
years: "1950s–1970",
yearStart: 1952,
countries: ["USA"],
agencies: ["CIA", "US Army"],
category: "Bioweapon / chemical",
status: "Proven — declassified",
summary: "Joint CIA-Army program to stockpile incapacitating and lethal biological/chemical materials and dissemination devices.",
details: "Revealed by the Church Committee. Covered dart guns, toxins and crop/animal pathogens. Materials reportedly destroyed after Nixon's 1969-70 bioweapon ban.",
sources: "Church Committee Book I"
},
{
id: "paperclip",
title: "Operation Paperclip",
years: "1945–1959",
yearStart: 1945,
countries: ["USA", "Germany"],
agencies: ["OSS", "CIA", "US Army"],
category: "Recruitment / cover-up",
status: "Proven — declassified",
summary: "Secret US recruitment of 1,600+ German scientists and engineers, including former Nazis, for Cold War research.",
details: "Included Wernher von Braun's rocket team. Security dossiers were sanitized to bypass denazification rules. Confirmed by JIOA records.",
sources: "JIOA records; National Archives"
},
{
id: "ajax-boot",
title: "Operation Ajax / Boot – Iran Coup",
years: "1953",
yearStart: 1953,
countries: ["USA", "UK", "Iran"],
agencies: ["CIA", "MI6"],
category: "Regime change",
status: "Proven — acknowledged",
summary: "US-UK covert operation that helped overthrow Iranian Prime Minister Mossadegh after oil nationalization.",
details: "CIA history declassified in 2013 confirms US role in planning protests, bribery and propaganda. MI6 handled parallel networks. The Shah returned to power.",
sources: "CIA Wilber history (declassified 2013); US State Dept FRUS"
},
{
id: "pbsuccess",
title: "Operation PBSUCCESS – Guatemala Coup",
years: "1954",
yearStart: 1954,
countries: ["USA", "Guatemala"],
agencies: ["CIA"],
category: "Regime change",
status: "Proven — declassified",
summary: "CIA psychological-warfare and paramilitary operation that toppled President Arbenz, defending United Fruit interests and anti-communism.",
details: "Used rebel force under Castillo Armas, clandestine radio (Voice of Liberation), air drops and assassination lists. Followed by decades of military rule.",
sources: "CIA PBSUCCESS history; State Dept FRUS"
},
{
id: "washtub",
title: "Operation Washtub",
years: "1954",
yearStart: 1954,
countries: ["USA", "Nicaragua"],
agencies: ["CIA"],
category: "Propaganda / false cache",
status: "Proven — declassified",
summary: "Staged Soviet arms cache in Nicaragua to link Guatemala to Moscow and justify PBSUCCESS.",
details: "CIA planted weapons to be 'discovered.' Later histories cite it as an early false-flag propaganda cache.",
sources: "CIA PBSUCCESS histories"
},
{
id: "mongoose",
title: "Operation Mongoose",
years: "1961–1963",
yearStart: 1961,
countries: ["USA", "Cuba"],
agencies: ["CIA", "DoD"],
category: "Sabotage / regime change",
status: "Proven — declassified",
summary: "Post-Bay of Pigs campaign of sabotage, propaganda and assassination planning against Castro's Cuba.",
details: "Authorized by Kennedy. Included economic sabotage, raids and CIA assassination plots documented in Church Committee and inspector-general reports.",
sources: "Church Committee; CIA IG assassination report (1967)"
},
{
id: "northwoods",
title: "Operation Northwoods (Proposed)",
years: "1962 (proposed, rejected)",
yearStart: 1962,
countries: ["USA", "Cuba"],
agencies: ["DoD", "JCS"],
category: "Proposed false-flag",
status: "Proven proposal — rejected, never executed",
summary: "Joint Chiefs proposal for staged attacks to justify invading Cuba. Rejected by President Kennedy.",
details: "Declassified 1997-98. Suggested hijackings, bombings and fake casualties blamed on Cuba. Important as a documented rejected plan, not an executed operation.",
sources: "JCS memo 13 March 1962 (NARA)"
},
{
id: "fubelt",
title: "Operation FUBELT – Chile",
years: "1970–1973",
yearStart: 1970,
countries: ["USA", "Chile"],
agencies: ["CIA"],
category: "Regime change",
status: "Proven — declassified",
summary: "CIA covert action to prevent Allende's inauguration and later destabilize his government before the 1973 coup.",
details: "Included Track I and Track II, funding opposition, propaganda and contacts linked to the Schneider assassination. US role confirmed in Hinchey Report and Clinton-era releases.",
sources: "Hinchey Report (2000); State Dept Chile Declassification Project"
},
{
id: "condor-support",
title: "US Support to Operation Condor",
years: "1975–1983",
yearStart: 1975,
countries: ["USA", "Argentina", "Chile", "Uruguay", "Paraguay", "Bolivia", "Brazil"],
agencies: ["CIA", "State Dept", "DoD"],
category: "Repression / intelligence sharing",
status: "Proven support — declassified",
summary: "South American dictatorships coordinated cross-border kidnapping and assassination; US provided intelligence, training and communications.",
details: "Condor itself was run by Southern Cone regimes. Declassified cables show US awareness and assistance. Exact foreknowledge of assassinations remains debated by historians.",
sources: "State Dept Condor cables; CIA declassifications"
},
{
id: "cyclone",
title: "Operation Cyclone – Afghanistan",
years: "1979–1989",
yearStart: 1979,
countries: ["USA", "Afghanistan", "Pakistan", "Saudi Arabia"],
agencies: ["CIA", "ISI"],
category: "Proxy war",
status: "Proven — acknowledged",
summary: "CIA program arming Afghan mujahideen via Pakistan, one of the longest covert operations of the Cold War.",
details: "Expanded under Reagan with Saudi matching funds. Included Stinger missiles. Long-term blowback debated by scholars.",
sources: "CIA histories; State Dept volumes; memoirs"
},
{
id: "iran-contra",
title: "Iran-Contra Affair",
years: "1981–1986",
yearStart: 1981,
countries: ["USA", "Iran", "Nicaragua"],
agencies: ["CIA", "NSC"],
category: "Arms trafficking / illegal funding",
status: "Proven — convictions / pardons",
summary: "Secret US arms sales to Iran funded Contra rebels despite congressional bans, violating stated policy and law.",
details: "Exposed 1986. Tower Commission, Walsh investigation and congressional hearings documented diversion of funds. Several officials convicted, later pardoned.",
sources: "Tower Commission; Walsh Report; Congressional report"
},
{
id: "cointelpro",
title: "COINTELPRO",
years: "1956–1971",
yearStart: 1956,
countries: ["USA"],
agencies: ["FBI"],
category: "Surveillance / repression",
status: "Proven — declassified",
summary: "FBI counterintelligence program targeting civil-rights, anti-war, Black nationalist, socialist and other domestic movements.",
details: "Exposed by 1971 Citizens' Commission burglary and Church Committee. Tactics included infiltration, forged letters, and attempts to cause splits and firings.",
sources: "Church Committee; FBI files"
},
{
id: "chaos",
title: "Operation CHAOS",
years: "1967–1974",
yearStart: 1967,
countries: ["USA"],
agencies: ["CIA"],
category: "Domestic surveillance",
status: "Proven — illegal, declassified",
summary: "CIA domestic spying on anti-war and student movements despite charter ban on domestic policing.",
details: "Compiled 7,000+ files. Rockefeller Commission found it improper. No evidence found of foreign control of protests, the original justification.",
sources: "Rockefeller Commission (1975)"
},
{
id: "shamrock",
title: "Project SHAMROCK",
years: "1945–1975",
yearStart: 1945,
countries: ["USA"],
agencies: ["NSA", "AFSA"],
category: "Signals intelligence / surveillance",
status: "Proven — illegal, declassified",
summary: "Warrantless collection of international telegrams via Western Union, RCA and ITT cooperation.",
details: "Revealed by Church Committee. NSA received microfilm copies daily. Ended 1975 after reforms.",
sources: "Church Committee Book III"
},
{
id: "minaret",
title: "Project MINARET",
years: "1967–1973",
yearStart: 1967,
countries: ["USA"],
agencies: ["NSA"],
category: "Signals intelligence / surveillance",
status: "Proven — illegal, declassified",
summary: "NSA watchlist surveillance of US anti-war, civil-rights leaders and journalists without warrants.",
details: "Included figures such as Martin Luther King Jr. and Muhammad Ali on watchlists. Exposed by Church Committee.",
sources: "Church Committee"
},
{
id: "mockingbird",
title: "Operation Mockingbird / Media Contacts",
years: "1950s–1970s",
yearStart: 1951,
countries: ["USA"],
agencies: ["CIA"],
category: "Propaganda / media",
status: "Partially proven — extent debated",
summary: "CIA cultivation of journalists and outlets for propaganda. Name comes from 1963 wiretap; scale remains contested.",
details: "Church Committee confirmed 50+ journalist relationships and media assets. Scholars distinguish documented contacts from broader unproven claims that all major media were controlled.",
sources: "Church Committee; Bernstein 1977 reporting (contested scope)"
},
{
id: "phoenix",
title: "Phoenix Program",
years: "1965–1972",
yearStart: 1965,
countries: ["USA", "South Vietnam"],
agencies: ["CIA", "US Army", "South Vietnam"],
category: "Counterinsurgency / assassination",
status: "Proven — acknowledged, toll disputed",
summary: "Campaign to neutralize Viet Cong infrastructure via capture, defection or killing; 20,000+ killed.",
details: "Defended as targeted intelligence program; critics cite torture and extrajudicial killing. US congressional hearings documented abuses.",
sources: "US Army histories; Congressional hearings"
},
{
id: "ranch-hand",
title: "Operation Ranch Hand / Agent Orange",
years: "1962–1971",
yearStart: 1962,
countries: ["USA", "Vietnam", "Laos", "Cambodia"],
agencies: ["US Air Force", "DoD"],
category: "Chemical warfare / defoliation",
status: "Proven — health effects acknowledged",
summary: "Aerial spraying of 70M+ liters of herbicides, contaminating land and exposing millions to dioxin.",
details: "VA presumes links to cancers and birth defects. US has funded remediation at Da Nang and Bien Hoa. Legality under chemical-weapons norms debated.",
sources: "USAF histories; VA; USAID remediation reports"
},
{
id: "popeye",
title: "Operation Popeye",
years: "1967–1972",
yearStart: 1967,
countries: ["USA", "Vietnam", "Laos"],
agencies: ["US Air Force", "CIA"],
category: "Weather modification",
status: "Proven — declassified",
summary: "Cloud-seeding to extend monsoon season and mire Ho Chi Minh Trail logistics.",
details: "Revealed 1971-74. Led to 1978 ENMOD treaty banning hostile environmental modification.",
sources: "Pentagon Papers references; Senate hearings"
},
{
id: "shad-112",
title: "Project 112 / Project SHAD",
years: "1962–1973",
yearStart: 1962,
countries: ["USA"],
agencies: ["DoD"],
category: "Bioweapon / chemical test",
status: "Proven — acknowledged 2000s",
summary: "Secret tests of chemical/biological agents and decontamination on ships and land, often without crew knowledge.",
details: "VA acknowledged 6,000+ exposed servicemembers. Declassified 2000-2003 after veteran pressure for care.",
sources: "DoD SHAD declassifications; VA"
},
{
id: "edgewood",
title: "Edgewood Arsenal Human Experiments",
years: "1948–1975",
yearStart: 1948,
countries: ["USA"],
agencies: ["US Army"],
category: "Human experiment",
status: "Proven — acknowledged",
summary: "7,000+ soldiers exposed to nerve agents, LSD, BZ and other chemicals to test protective gear and incapacitants.",
details: "Volunteers gave limited consent with incomplete risk disclosure by modern standards. Institute of Medicine later reviewed health effects.",
sources: "Army histories; IOM reports"
},
{
id: "radiation-experiments",
title: "US Human Radiation Experiments",
years: "1944–1974",
yearStart: 1944,
countries: ["USA"],
agencies: ["AEC", "DoD"],
category: "Human experiment",
status: "Proven — acknowledged",
summary: "Plutonium injections, total-body irradiation and fallout studies on patients, soldiers and civilians without proper consent.",
details: "Confirmed by 1994-95 Advisory Committee. Included 18 plutonium injections and Cincinnati irradiation studies. Clinton apologized and compensated some victims.",
sources: "ACHRE Final Report (1995)"
},
{
id: "tuskegee",
title: "Tuskegee Syphilis Study",
years: "1932–1972",
yearStart: 1932,
countries: ["USA"],
agencies: ["US Public Health Service"],
category: "Human experiment",
status: "Proven — acknowledged",
summary: "Black men with syphilis left untreated to study disease progression, even after penicillin became standard.",
details: "399 men enrolled, deceived. Exposed 1972 by press. Led to Belmont Report and IRB reforms. Clinton formally apologized 1997.",
sources: "CDC histories; Presidential apology records"
},
{
id: "guatemala-syphilis",
title: "Guatemala Syphilis Experiments",
years: "1946–1948",
yearStart: 1946,
countries: ["USA", "Guatemala"],
agencies: ["US PHS"],
category: "Human experiment",
status: "Proven — acknowledged",
summary: "US researchers deliberately infected prisoners, soldiers and psychiatric patients with syphilis and gonorrhea without consent.",
details: "Led by John Cutler, uncovered 2010 by Susan Reverby. Obama apologized; US settled scientific-ethics reviews condemned it.",
sources: "Presidential Commission report (2011)"
},
{
id: "sea-spray",
title: "Operation Sea-Spray",
years: "1950",
yearStart: 1950,
countries: ["USA"],
agencies: ["US Navy"],
category: "Bioweapon test / open-air",
status: "Proven — declassified",
summary: "Spraying of Serratia and Bacillus from ships over San Francisco to simulate bioweapon attack.",
details: "Public learned via 1976-77 Senate hearings. One death from infection is alleged but causal link remains medically debated; Navy deemed bacteria 'harmless' at the time.",
sources: "Senate biowarfare hearings (1977)"
},
{
id: "lac-dew",
title: "Operation LAC / Operation Dew",
years: "1951–1958",
yearStart: 1951,
countries: ["USA"],
agencies: ["US Army Chemical Corps"],
category: "Chemical dispersal test",
status: "Proven — declassified",
summary: "Zinc cadmium sulfide dispersal over St. Louis, Minneapolis and other areas to model chemical-weapon spread.",
details: "Residents not informed. Army said simulant was harmless; later reviews questioned cadmium toxicity. St. Louis spraying included low-income Pruitt-Igoe housing.",
sources: "Army reports; National Research Council reviews"
},
{
id: "gladio",
title: "Operation Gladio / Stay-Behind Networks",
years: "1956–1990",
yearStart: 1956,
countries: ["Italy", "NATO", "Belgium", "Turkey", "Greece"],
agencies: ["CIA", "MI6", "NATO", "SISMI"],
category: "Paramilitary stay-behind",
status: "Proven existence — crimes disputed",
summary: "NATO-linked secret caches and paramilitary cells to resist Soviet invasion; some linked by investigators to domestic terrorism.",
details: "Confirmed by Italian PM Andreotti 1990 and European Parliament resolution. Direct CIA/NATO control of bombings alleged but not judicially proven for most attacks.",
sources: "Italian parliamentary reports; EU Parliament resolution 1990"
},
{
id: "legacy",
title: "Operation Legacy – Colonial File Destruction",
years: "1950s–1970s",
yearStart: 1950,
countries: ["UK", "Kenya", "Malaya", "Cyprus", "Others"],
agencies: ["Colonial Office", "MI5"],
category: "Cover-up / colonial",
status: "Proven — acknowledged 2011-13",
summary: "Systematic burning and hiding of colonial files documenting abuse to keep them from successor governments.",
details: "Revealed during Mau Mau veterans' lawsuit. 8,800+ files from 37 colonies hidden at Hanslope Park. Foreign Office apologized for handling.",
sources: "Hanslope disclosure; High Court Mau Mau case"
},
{
id: "mau-mau-hola",
title: "Mau Mau Suppression / Hola Camp",
years: "1952–1960",
yearStart: 1952,
countries: ["UK", "Kenya"],
agencies: ["British Army", "Colonial administration"],
category: "Colonial counterinsurgency",
status: "Proven — acknowledged, compensated",
summary: "Brutal suppression of Kenyan uprising with mass detention, torture and the 1959 Hola Camp beating of 11 detainees.",
details: "1.5M Kikuyu in villagization. UK paid £19.9M to 5,228 survivors in 2013. Historians estimate tens of thousands killed.",
sources: "UK Foreign Office settlement (2013); Anderson/Elkins histories"
},
{
id: "batang-kali",
title: "Batang Kali / Malayan Emergency",
years: "1948–1960",
yearStart: 1948,
countries: ["UK", "Malaya"],
agencies: ["British Army", "Scots Guards"],
category: "Colonial counterinsurgency",
status: "Proven killings — no prosecution",
summary: "1948 killing of 24 unarmed villagers by Scots Guards; subsequent cover-up and failed prosecutions.",
details: "Briggs Plan also forcibly resettled 400,000+ into New Villages. UK Supreme Court 2015 declined inquiry but did not dispute deaths occurred.",
sources: "UK court records; Malayan Emergency histories"
},
{
id: "aden-interrogation",
title: "Aden Emergency Interrogation Centre",
years: "1963–1967",
yearStart: 1963,
countries: ["UK", "Yemen (Aden)"],
agencies: ["British Army", "Intelligence Corps"],
category: "Torture / counterinsurgency",
status: "Proven — investigated",
summary: "Fort Morbut centre where detainees were stripped, kept in cold cells and beaten; Red Cross and Amnesty documented abuse.",
details: "Bowen inquiry and Amnesty 1966 report confirmed ill-treatment. UK ministers denied systematic torture at the time.",
sources: "Amnesty 1966; UK National Archives"
},
{
id: "mrf-ni",
title: "Military Reaction Force – Northern Ireland",
years: "1971–1973",
yearStart: 1971,
countries: ["UK", "Northern Ireland"],
agencies: ["British Army"],
category: "Covert counterinsurgency",
status: "Proven unit — shootings investigated",
summary: "Plainclothes Army unit conducting surveillance and drive-by operations; linked to civilian shootings.",
details: "Admitted 1970s. BBC Panorama and 2013-15 investigations linked MRF to 10+ unarmed shootings. PSNI legacy investigations ongoing.",
sources: "UK MoD statements; Panorama investigations"
},
{
id: "jtrig",
title: "JTRIG – GCHQ Online Manipulation",
years: "2010–2014 (revealed)",
yearStart: 2010,
countries: ["UK", "USA", "Five Eyes"],
agencies: ["GCHQ", "NSA"],
category: "Surveillance / propaganda",
status: "Proven — Snowden leaks",
summary: "Joint Threat Research Intelligence Group tactics for online deception, honeypots and influence revealed by Snowden.",
details: "Slides show DDoS, false personas and discrediting targets. GCHQ neither confirmed nor denied specifics but program architecture authenticated.",
sources: "Snowden documents via The Intercept/NBC (2014)"
},
{
id: "porton-down",
title: "Porton Down Volunteer Experiments",
years: "1949–1989",
yearStart: 1949,
countries: ["UK"],
agencies: ["MI6", "Army", "Porton Down"],
category: "Human experiment",
status: "Proven — acknowledged, 1 unlawful killing ruling",
summary: "20,000+ servicemen exposed to sarin, LSD and nerve agents; airman Ronald Maddison died from sarin in 1953.",
details: "2004 inquest ruled unlawful killing. 2008 MoD settled 360 claims (£3M). Open-air germ releases over Dorset also documented.",
sources: "UK inquest (2004); MoD settlement"
},
{
id: "embarrass",
title: "Operation Embarrass – MI6 Palestine",
years: "1948",
yearStart: 1948,
countries: ["UK", "Palestine", "Italy"],
agencies: ["MI6"],
category: "Sabotage",
status: "Proven — declassified",
summary: "MI6 bomb attacks on ships carrying Jewish refugees and arms to Palestine to preserve British mandate policy.",
details: "Five ships sabotaged in Italian ports. Revealed via declassified files and historian Keith Jeffery's MI6 history (2010).",
sources: "UK National Archives; Jeffery MI6 history"
},
{
id: "rainbow-warrior",
title: "Rainbow Warrior Sinking",
years: "1985",
yearStart: 1985,
countries: ["France", "New Zealand"],
agencies: ["DGSE"],
category: "Sabotage / assassination",
status: "Proven — admitted",
summary: "French agents bombed Greenpeace ship protesting nuclear tests, killing photographer Fernando Pereira.",
details: "France initially denied, then admitted. Two agents convicted in NZ; France paid $7M+ to NZ and Greenpeace. Defence minister resigned.",
sources: "NZ court convictions; French admission"
},
{
id: "algiers-torture",
title: "Battle of Algiers – Torture System",
years: "1954–1962",
yearStart: 1954,
countries: ["France", "Algeria"],
agencies: ["French Army", "DST"],
category: "Torture / colonial war",
status: "Proven — acknowledged 2018",
summary: "Systematic torture, disappearances and summary executions during Algerian War, including under Gen. Massu in Algiers.",
details: "Henri Alleg's La Question (1958) exposed methods. Macron 2018 admitted systematic torture and acknowledged murder of Maurice Audin.",
sources: "French presidential admission (2018); historiography"
},
{
id: "barracuda",
title: "Operation Barracuda – Central African Empire",
years: "1979",
yearStart: 1979,
countries: ["France", "Central African Republic"],
agencies: ["French Army", "DGSE"],
category: "Regime change",
status: "Proven — acknowledged",
summary: "French paratroopers deposed Emperor Bokassa while he visited Libya, restoring Dacko to power.",
details: "France had long backed Bokassa. Diamonds affair and Ngaragba prison massacre prompted intervention. Troops secured Bangui airport then capital.",
sources: "French government statements; histories"
},
{
id: "francafrique-chad",
title: "Françafrique Network / Chad Interventions",
years: "1960s–1990s",
yearStart: 1968,
countries: ["France", "Chad", "Gabon", "Others"],
agencies: ["DGSE", "Elysée Africa cell"],
category: "Neocolonial intervention",
status: "Proven pattern — specifics debated",
summary: "Decades of French military, financial and intelligence ties propping allied African leaders and ousting rivals.",
details: "Includes Operations Manta (1983) and Épervier in Chad, Bongo system in Gabon. Critics cite corruption; defenders cite stability agreements. Scholars document extensive covert funding.",
sources: "French parliamentary missions; academic histories"
},
{
id: "gal-spain",
title: "GAL Death Squads – Spain",
years: "1983–1987",
yearStart: 1983,
countries: ["Spain", "France"],
agencies: ["Spanish Interior Ministry", "Police"],
category: "State terrorism / assassination",
status: "Proven — convictions",
summary: "Government-funded mercenaries kidnapped and killed ETA suspects in France; 27 killed.",
details: "Exposed by press. Interior Minister Barrionuevo and security chief Vera convicted 1998. Seen as democratic Spain's illegal anti-terror campaign.",
sources: "Spanish Supreme Court convictions (1998)"
},
{
id: "echelon",
title: "ECHELON / Five Eyes Collection",
years: "1960s–present (revealed 1988–2000)",
yearStart: 1966,
countries: ["USA", "UK", "Canada", "Australia", "New Zealand"],
agencies: ["NSA", "GCHQ", "CSE", "ASD", "GCSB"],
category: "Signals intelligence",
status: "Proven — acknowledged, scope debated",
summary: "Global satellite and cable interception network sharing intelligence among Five Eyes.",
details: "Revealed by Duncan Campbell (1988) and EU STOA reports (1997-2001). Governments confirmed cooperation but dispute industrial-espionage claims.",
sources: "EU STOA reports; Campbell investigations"
},
{
id: "prism-upstream",
title: "PRISM / Upstream – Snowden Revelations",
years: "2007–2013 (revealed)",
yearStart: 2007,
countries: ["USA", "UK"],
agencies: ["NSA", "GCHQ", "FBI"],
category: "Mass surveillance",
status: "Proven — leaked, partially reformed",
summary: "Court-supervised but broad collection from tech companies and internet backbone, exposed by Edward Snowden.",
details: "FISA Court authorized; critics called it mass surveillance. USA Freedom Act (2015) ended bulk telephony program. Tech firms disputed direct server access framing.",
sources: "Snowden documents; PCLOB reports"
},
{
id: "stellar-wind",
title: "Stellar Wind / Warrantless Wiretapping",
years: "2001–2007",
yearStart: 2001,
countries: ["USA"],
agencies: ["NSA", "DOJ"],
category: "Mass surveillance",
status: "Proven — illegal ruling (2015)",
summary: "Post-9/11 secret program for warrantless email and phone metadata collection authorized by Bush.",
details: "Revealed 2005. DOJ revolt 2004 (Ashcroft hospital standoff). Appeals court 2015 ruled bulk telephony illegal.",
sources: "DOJ IG reports; 2nd Circuit ruling 2015"
},
{
id: "allan-memorial",
title: "Allan Memorial / Montreal Experiments",
years: "1957–1964",
yearStart: 1957,
countries: ["Canada", "USA"],
agencies: ["CIA", "McGill University"],
category: "Mind control / human experiment",
status: "Proven — settled",
summary: "Dr. Ewen Cameron's psychic driving with LSD, electroshock and induced comas on psychiatric patients, funded via CIA front.",
details: "Subproject 68 of MKUltra. Canadian government paid $100K+ to 250+ victims in 1990s-2000s. CIA settlement 1988 for 9 victims.",
sources: "Canadian settlements; Senate hearings"
},
{
id: "suez-sevres",
title: "Suez Collusion / Protocol of Sèvres",
years: "1956",
yearStart: 1956,
countries: ["UK", "France", "Israel", "Egypt"],
agencies: ["MI6", "DGSE", "Mossad"],
category: "Secret war plot",
status: "Proven — admitted",
summary: "Secret pact for Israel to attack Sinai as pretext for Anglo-French seizure of Suez Canal after Nasser's nationalization.",
details: "Denied for decades, confirmed by British and French sources 1980s-2000s. Collapsed under US-Soviet pressure; Eden resigned.",
sources: "UK/French archives; Dayan memoirs"
},
{
id: "strategy-tension",
title: "Strategy of Tension – Italy (Context)",
years: "1969–1980",
yearStart: 1969,
countries: ["Italy", "USA"],
agencies: ["Various: neo-fascists, P2, rogue services"],
category: "Terrorism / disputed attribution",
status: "Bombings proven — Gladio link unproven",
summary: "Wave of bombings (Piazza Fontana 1969, Bologna 1980) used to justify crackdowns. Far-right and later far-left convicted; state-mastermind claims disputed.",
details: "Courts convicted Ordine Nuovo members for Piazza Fontana and NAR for Bologna. Parliamentary inquiries found intelligence obstruction but no court proved CIA/Gladio ordered bombings. Include as contested case study.",
sources: "Italian court verdicts; Parliamentary Massacres Commission"
}
];
