const ARCHIVE2 = [
{
id: "zapata-bayofpigs",
title: "Operation Zapata – Bay of Pigs",
years: "1961",
yearStart: 1961,
countries: ["USA", "Cuba"],
agencies: ["CIA"],
category: "Regime change / paramilitary",
status: "Proven — declassified",
summary: "CIA-trained 1,400-man Brigade 2506 invasion of Cuba that collapsed in 3 days.",
details: "Authorized by Eisenhower, approved by Kennedy. CIA provided air, ships and training in Guatemala/Nicaragua. Poor air cover and underestimation of Castro support caused defeat. Taylor Report and CIA IG blamed planning. Led directly to Mongoose escalation.",
sources: "CIA IG Bay of Pigs history; Taylor Report; FRUS"
},
{
id: "htlingual",
title: "Operation HTLINGUAL – CIA Mail Opening",
years: "1952–1973",
yearStart: 1952,
countries: ["USA"],
agencies: ["CIA"],
category: "Domestic surveillance",
status: "Proven — illegal, declassified",
summary: "CIA opened 215,000+ letters to/from USSR without warrants.",
details: "Run from New York JFK facility under Angleton. Violated statutes. Exposed by Hersh and Church Committee, ended 1973. Helped prompt FISA and mail-privacy reforms.",
sources: "Church Committee Book III; Rockefeller Report"
},
{
id: "kubark-manual",
title: "KUBARK Interrogation Manual",
years: "1963–1980s",
yearStart: 1963,
countries: ["USA", "Latin America", "Vietnam"],
agencies: ["CIA"],
category: "Torture doctrine",
status: "Proven — declassified",
summary: "CIA torture/coercion manual teaching electric shock threats, isolation and degradation.",
details: "Declassified 1994-97. Basis for 1983 Honduras manual. Used in Vietnam, Latin America and later cited in Torture Report lineage. Proves institutional teaching of coercion, later disavowed.",
sources: "CIA KUBARK (1963) NARA release"
},
{
id: "black-sites",
title: "CIA Black Sites / Enhanced Interrogation",
years: "2002–2009",
yearStart: 2002,
countries: ["USA", "Thailand", "Poland", "Romania", "Others"],
agencies: ["CIA"],
category: "Torture / detention",
status: "Proven — Senate report",
summary: "Secret prisons using waterboarding, sleep deprivation and walling on 119 detainees.",
details: "Authorized post-9/11 via OLC memos. Senate Torture Report (2014, 525pp public) found brutality and no unique intel. Obama banned 2009. No prosecutions; Poland/ECtHR ruled violations, paid victims.",
sources: "SSCI Torture Report (2014); ECtHR rulings"
},
{
id: "rendition",
title: "Extraordinary Rendition Program",
years: "1995–2013",
yearStart: 1995,
countries: ["USA", "Egypt", "Sweden", "Italy", "Others"],
agencies: ["CIA"],
category: "Kidnapping / transfer",
status: "Proven — acknowledged",
summary: "CIA seizure and transfer of suspects to foreign jails for harsh interrogation.",
details: "Started Clinton-era, expanded post-9/11. Italy convicted 23 Americans in absentia for 2003 Abu Omar Milan abduction. Sweden, UK and Council of Europe inquiries confirmed complicity. Obama curtailed, Jeppesen lawsuit dismissed on secrets grounds.",
sources: "Open Society/Council of Europe reports; Milan convictions 2009"
},
{
id: "ivy-bells",
title: "Operation Ivy Bells – Soviet Cable Tap",
years: "1970s–1981",
yearStart: 1971,
countries: ["USA", "USSR"],
agencies: ["US Navy", "NSA"],
category: "Signals intelligence",
status: "Proven — acknowledged",
summary: "US subs tapped Soviet Okhotsk undersea cables, recording unencrypted traffic.",
details: "Divers planted pods retrieved yearly. Compromised 1981 by NSA clerk Ronald Pelton selling to KGB. Success proved by Navy histories; shifted Soviets to encryption. Classic high-risk Cold War SIGINT win.",
sources: "Navy histories; Pelton espionage case"
},
{
id: "gold-tunnel",
title: "Operation Gold – Berlin Tunnel",
years: "1954–1956",
yearStart: 1954,
countries: ["USA", "UK", "Germany", "USSR"],
agencies: ["CIA", "MI6"],
category: "Signals intelligence",
status: "Proven — acknowledged",
summary: "500m CIA/MI6 tunnel to tap Soviet Berlin phone cables.",
details: "Joint CIA-MI6 build, $6M+. KGB mole George Blake betrayed it from start; Soviets let it run to protect him, feeding disinfo. Discovered 1956 amid propaganda. Valuable despite compromise; confirmed by both sides.",
sources: "CIA histories; Blake memoir; BStU files"
},
{
id: "valuable-albania",
title: "Operation Valuable – Albania",
years: "1949–1953",
yearStart: 1949,
countries: ["UK", "USA", "Albania"],
agencies: ["MI6", "CIA"],
category: "Regime change / infiltration",
status: "Proven — failed, declassified",
summary: "MI6/CIA infiltration of communist Albania using exiles; 300+ killed.",
details: "Trained Balli Kombetar exiles, Sazan Island drops. Betrayed by Kim Philby. Survivors executed. Official MI6 history (Jeffery 2010) confirms. Early Cold War rollback disaster ending such attempts.",
sources: "Jeffery MI6 history; CIA histories"
},
{
id: "st-circus",
title: "ST CIRCUS – CIA in Tibet",
years: "1956–1972",
yearStart: 1956,
countries: ["USA", "Tibet", "Nepal"],
agencies: ["CIA"],
category: "Proxy war",
status: "Proven — acknowledged",
summary: "CIA armed/trained Tibetan Khampa guerrillas and Dalai Lama's 1959 escape.",
details: "Colorado Camp Hale training, airdrops, Mustang base in Nepal. $1.7M/year at peak per declassified memos. Ended with Nixon-Mao rapprochement. Dalai Lama admitted funds. Limited effect, major symbolic support.",
sources: "State Dept FRUS; CIA histories"
},
{
id: "indonesia-1958",
title: "CIA Indonesia Rebellion Support",
years: "1957–1958",
yearStart: 1957,
countries: ["USA", "Indonesia"],
agencies: ["CIA"],
category: "Proxy war / regime change",
status: "Proven — pilot captured",
summary: "CIA backed Permesta/PRRI rebels with bombers; pilot Allen Pope shot down.",
details: "Eisenhower authorized to weaken Sukarno. CIA B-26s bombed towns. Pope captured May 1958 with US docs, exposing role. US shifted to Jakarta, Pope jailed then released. Confirmed by FRUS and Pope trial.",
sources: "FRUS Indonesia; Pope trial records"
},
{
id: "brother-sam",
title: "Operation Brother Sam – Brazil",
years: "1964",
yearStart: 1964,
countries: ["USA", "Brazil"],
agencies: ["DoD", "CIA", "State Dept"],
category: "Coup support",
status: "Proven — declassified",
summary: "US naval task force and arms/fuel staged to back 1964 overthrow of Goulart.",
details: "Ambassador Gordon requested; carrier Forrestal and destroyers dispatched. Coup succeeded before intervention needed. Declassified cables confirm US readiness and funding of opposition. Followed by 21-year dictatorship.",
sources: "LBJ Library cables; National Security Archive"
},
{
id: "pbfortune",
title: "Operation PBFORTUNE – Guatemala Precursor",
years: "1952",
yearStart: 1952,
countries: ["USA", "Guatemala", "Nicaragua"],
agencies: ["CIA"],
category: "Regime change (aborted)",
status: "Proven — declassified",
summary: "1952 CIA plan with Somoza to invade Guatemala; halted when exposed.",
details: "Authorized by Truman, involved arms to Castillo Armas. CIA halted after weapons seizure publicity. Direct predecessor proving Guatemala plotting predated Eisenhower. Confirmed in CIA histories.",
sources: "CIA histories; FRUS Guatemala"
},
{
id: "soa-manuals",
title: "School of the Americas / Torture Manuals",
years: "1982–1991 (manuals)",
yearStart: 1982,
countries: ["USA", "Latin America"],
agencies: ["DoD", "CIA"],
category: "Training / doctrine",
status: "Proven — manuals released",
summary: "US Army school trained 60,000+ Latin officers; 1980s manuals taught coercion and execution.",
details: "Pentagon released 7 manuals 1996 after Baltimore Sun FOIA. Graduates include Condor and death-squad officers. Army disavowed, revised curriculum, renamed WHINSEC 2001. Link to specific atrocities is correlational but training content is proven.",
sources: "DoD manuals (1996 release); GAO reports"
},
{
id: "my-lai",
title: "My Lai Massacre + Cover-up",
years: "1968–1969",
yearStart: 1968,
countries: ["USA", "Vietnam"],
agencies: ["US Army"],
category: "War crime / cover-up",
status: "Proven — convictions",
summary: "US troops killed 347-504 civilians; chain of command covered up for a year.",
details: "Calley platoon, 16 March 1968. Helicopter pilot Hugh Thompson stopped killings. Ron Ridenhour letter forced probe. Peers Inquiry confirmed cover-up. Calley convicted, under house arrest, paroled. US paid victims. Defining Vietnam atrocity case.",
sources: "Peers Report; court-martial records"
},
{
id: "tiger-force",
title: "Tiger Force Atrocities",
years: "1967",
yearStart: 1967,
countries: ["USA", "Vietnam"],
agencies: ["US Army"],
category: "War crime",
status: "Proven — Army investigation",
summary: "Elite platoon killed 100+ civilians in Quang Ngai; Army buried probe.",
details: "Toledo Blade 2003 exposed 1971-75 Army CID file documenting torture and mutilation. No prosecutions. Army confirmed records. Shows systemic under-prosecution beyond My Lai.",
sources: "Army CID file; Toledo Blade Pulitzer 2004"
},
{
id: "underworld",
title: "Operation Underworld – Navy-Mafia Pact",
years: "1942–1945",
yearStart: 1942,
countries: ["USA", "Italy"],
agencies: ["US Navy", "OSS"],
category: "Criminal alliance",
status: "Proven — acknowledged",
summary: "Navy freed Lucky Luciano to secure NY docks and Sicily invasion help.",
details: "After Normandie fire, ONI enlisted Meyer Lansky to contact Luciano. Commuted 1946, deported. Herlands Inquiry (1954) confirmed cooperation. Mafia gained postwar Sicilian leverage. Early state-crime pact precedent.",
sources: "Herlands Report (1954); Navy histories"
},
{
id: "acoustic-kitty",
title: "Acoustic Kitty",
years: "1960s",
yearStart: 1961,
countries: ["USA"],
agencies: ["CIA"],
category: "Surveillance tech (failed)",
status: "Proven — declassified, failed",
summary: "CIA implanted cat with mic/transmitter to spy on Soviets; $20M, failed.",
details: "Declassified 2001 memo: 5-year effort, cat released near Soviet compound, reportedly hit by taxi on first mission. Closed 1967 as impractical. Proves exotic Cold War R&D waste, not urban legend.",
sources: "CIA CREST memo (1967 release 2001)"
},
{
id: "resistance-campus",
title: "Project RESISTANCE – CIA Campus Spying",
years: "1967–1973",
yearStart: 1967,
countries: ["USA"],
agencies: ["CIA"],
category: "Domestic surveillance",
status: "Proven — illegal",
summary: "CIA monitored student dissent, compiled files without authority.",
details: "Companion to CHAOS, run by Security Office. Rockefeller and Church found improper. Ended 1973-74. Led to campus-informant bans.",
sources: "Rockefeller Report; Church Committee"
},
{
id: "conus-intel",
title: "Army CONUS Surveillance",
years: "1967–1970",
yearStart: 1967,
countries: ["USA"],
agencies: ["US Army"],
category: "Domestic surveillance",
status: "Proven — exposed",
summary: "Army spied on 100,000+ civilians, MLK marches and conventions.",
details: "Exposed by Christopher Pyle (1970) and Ervin hearings. Files at Fort Holabird. Ordered destroyed 1970. Led to strict Posse Comitatus and intel limits on military domestic role.",
sources: "Ervin hearings (1971); Pyle reporting"
},
{
id: "noriega-panama",
title: "Noriega Asset + Operation Just Cause",
years: "1967–1989",
yearStart: 1967,
countries: ["USA", "Panama"],
agencies: ["CIA", "DEA", "DoD"],
category: "Asset blowback / invasion",
status: "Proven — invasion, trial",
summary: "CIA-paid Noriega turned drug lord; US invaded 1989, seized him.",
details: "Paid $100k+/year while trafficking. Indicted 1988. 27,000 troops invaded Dec 1989, 500+ Panamanians dead. Noriega convicted Miami 1992. Classic blowback case.",
sources: "Kerry Report (1988); SOUTHCOM histories"
},
{
id: "urgent-fury",
title: "Operation Urgent Fury – Grenada",
years: "1983",
yearStart: 1983,
countries: ["USA", "Grenada", "Cuba"],
agencies: ["DoD", "CIA"],
category: "Regime change / invasion",
status: "Proven — acknowledged",
summary: "7,000 US troops toppled Marxist regime after Bishop murder, citing students.",
details: "UN condemned as violation; US cited OECS request and Cuban barracks. 19 US, 70+ Grenadian/Cuban dead. Reagan popularity boost. Declassified planning shows pretext debate but legality contested, facts proven.",
sources: "DoD histories; UNGA Res 38/7"
},
{
id: "hooded-men",
title: "Hooded Men / Ballymurphy – NI Torture",
years: "1971",
yearStart: 1971,
countries: ["UK", "Northern Ireland"],
agencies: ["British Army", "RUC"],
category: "Torture",
status: "Proven torture — ECHR/Irish SC",
summary: "14 internees hooded, wall-standing, noise and beaten; Ballymurphy 11 shot.",
details: "Compton/Parker inquiries admitted ill-treatment. ECHR 1978: inhuman/degrading (torture by 2021 reading). Irish Supreme Court 2014-21 proved authorization at minister level. UK apologized 2021. No prosecutions.",
sources: "ECHR Ireland v UK; Parker Report"
},
{
id: "bloody-sunday",
title: "Bloody Sunday – Derry",
years: "1972–2010",
yearStart: 1972,
countries: ["UK", "Northern Ireland"],
agencies: ["British Army"],
category: "Killings / cover-up",
status: "Proven — inquiry, apology",
summary: "Paras shot 26 unarmed marchers, 14 dead; Widgery whitewash, Saville truth.",
details: "30 Jan 1972. Widgery 1972 largely exonerated. Saville 2010: unjustified, Cameron apologized. One prosecution (Soldier F) collapsed. Defining Troubles accountability case.",
sources: "Saville Report (2010); Cameron apology"
},
{
id: "turquoise-rwanda",
title: "Operation Turquoise – Rwanda",
years: "1994",
yearStart: 1994,
countries: ["France", "Rwanda", "Zaire"],
agencies: ["French Army"],
category: "Intervention (contested)",
status: "Proven deployment — intent debated",
summary: "2,500 French troops in safe zone during genocide; saved some, let killers flee.",
details: "UN-mandated. Duclert Report (2021): France bears heavy responsibility for blindness to genocide, no proven complicity in planning. Critics allege protection of Hutu regime; defenders cite rescues. Include as contested humanitarian/military case.",
sources: "Duclert Report (2021); UN records"
},
{
id: "fast-furious",
title: "Operation Fast and Furious",
years: "2009–2011",
yearStart: 2009,
countries: ["USA", "Mexico"],
agencies: ["ATF", "DOJ"],
category: "Gunwalking scandal",
status: "Proven — IG condemned",
summary: "ATF let 2,000 guns walk to track cartels; lost them, Border Patrol agent killed.",
details: "Phoenix-based. IG 2012 found reckless tactics, no high-level authorization proven. Holder held in contempt 2012. Mexico demanded answers. Reforms ended gunwalking.",
sources: "DOJ IG Report (2012)"
}
];
