const EXTRA_C = {
"edgewood": "Army 1948-75 studies at Aberdeen: 7,000+ volunteers exposed to sarin, VX, mustard, LSD, BZ to test gear and antidotes. Signed consent but incomplete disclosure plus rank pressure by modern standards. No deaths on site. Reviewed by Institute of Medicine; ended 1975. Congress authorized notification and follow-up — core to military research-ethics reform.",
"radiation-experiments": "AEC/Manhattan successors/DoD/hospitals studied plutonium metabolism, fallout and radiotherapy: 18 plutonium injections at Rochester/Chicago/SF without meaningful consent, total-body irradiation at Cincinnati/Oak Ridge, prisoner testicular irradiation, fallout ingestion. Thousands affected. Exposed by Welsome (1993) and O'Leary openness; Clinton's 1995 Advisory Committee, apology and compensation; strengthened human-subjects rules.",
"tuskegee": "PHS 1932-72 study of untreated syphilis in 600 Black Alabama men (399 ill), promised care while withholding diagnosis and penicillin after it became standard, causing deaths and congenital infections. Exposed by Buxtun/Heller 1972, ended after hearings. Led to 1974 National Research Act, Belmont Report and IRBs. Clinton apologized 1997; survivors compensated.",
"guatemala-syphilis": "PHS/PASB 1946-48: Cutler deliberately exposed ~1,500 prisoners/soldiers/patients via paid sex workers and inoculation to test penicillin prophylaxis, many untreated, no consent. Hidden in papers, found by Reverby 2010. Obama/Clinton apologized; 2011 bioethics commission condemned as unconscionable. Guatemalan US-court suit dismissed.",
"sea-spray": "Navy 1950 vulnerability test: ships sprayed Serratia/Bacillus off San Francisco, exposing ~800,000. Then deemed harmless simulants. Revealed in 1976-77 Senate hearings; one hospital Serratia death alleged but causal link disputed. Landmark open-air testing-ethics case.",
"lac-dew": "Army Chemical Corps 1951-58 dispersed zinc cadmium sulfide over St. Louis (including Pruitt-Igoe), Minneapolis and coasts to model Soviet spread. Residents uninformed. Later Army reports and NRC reviews found no proven cluster but inadequate safety evidence for cadmium — key secrecy and environmental-justice example.",
"gladio": "NATO/CIA/MI6 stay-behind caches and cells for Soviet invasion, best documented in Italy (Andreotti acknowledged 1990, EU resolution). Hundreds trained. Politicians alleged orchestration of bombings, but courts never proved CIA/NATO ordered major attacks. Proven as clandestine program; criminal responsibility disputed.",
"legacy": "Colonial Office decolonization directive to burn/dump/ship files to hide abuse. Scale emerged in Mau Mau suit: 8,800 files from 37 colonies hidden at Hanslope Park (disclosed 2011-13). Cary report confirmed systematic destruction. UK apologized, moved files to National Archives.",
"mau-mau-hola": "1952-60 suppression: emergency, mass detention, 1.5M Kikuyu villagization, torture and executions. Hola 1959 guards beat 11 to death, Parliament scandal. Elkins/Anderson histories, High Court suit. 2013 UK acknowledged torture, apologized, paid £19.9M to 5,228 survivors.",
"batang-kali": "1948 Malaya: Scots Guards killed 24 unarmed rubber workers; claimed escape attempt, survivors alleged massacre. 1949/1970 probes cleared patrol. Briggs Plan moved 400,000+ to New Villages. Revived 2000s; Supreme Court 2015 declined new inquiry without disputing deaths. No prosecution — acknowledged but unresolved.",
"aden-interrogation": "1963-67 Fort Morbut centre: stripping, cold/noise, stress positions, beatings to extract intel before 1967 withdrawal. Red Cross and Amnesty 1966 documented abuse; Bowen inquiry confirmed some ill-treatment, ministers denied systematic torture. Later files corroborated harsh methods; shaped interrogation doctrine and Amnesty's rise.",
"mrf-ni": "Army plainclothes MRF in Belfast 1971-73 for surveillance and IRA disruption via unmarked cars. Admitted generally in 1970s; Panorama and later probes linked members to shootings killing/wounding unarmed civilians (10+ deaths investigated). MoD says lawful; PSNI legacy inquests continue, liability disputed."
};
