const EXTRA_B = {
"condor-support": "1975-1983 pact of Chile, Argentina, Uruguay, Paraguay, Bolivia, Brazil to kidnap/torture/assassinate opponents across borders (hundreds dead). US motive: anti-communist stability. Declassified cables show detailed US knowledge, provision of communications, training and Panama liaison, plus tolerance. Kissinger's 1976 demarche debate continues. Letelier's 1976 DC car-bomb is the best-known Condor murder. US role proven as support/awareness, not operational command.",
"cyclone": "CIA program 1979-1989 arming Afghan mujahideen via Pakistan's ISI, with Saudi matching funds. Carter-authorized, Reagan-expanded: rifles, mortars, training, satellite intel and from 1986 Stingers that blunted Soviet air power. Forced 1989 Soviet withdrawal. Successful proxy war, but ISI favoritism to Islamists and leftover weapons/funds shaped later Taliban/jihadist networks (direct creation of al-Qaeda not established).",
"iran-contra": "1985-86 secret arms sales to Iran (TOWs, Hawks via Israel) to free Lebanon hostages, proceeds diverted to Contras despite Boland bans. Run by Poindexter, North and Casey. Exposed 1986, probed by Tower Commission, Congress and Walsh. 14 charged, 11 convicted; overturned or pardoned by Bush 1992. Reaffirmed congressional funding controls and damaged Reagan credibility.",
"cointelpro": "Hoover-authorized 1956-1971 FBI program to disrupt CPUSA then civil-rights, Black nationalist, anti-war and socialist movements. Used infiltration, wiretaps, forged letters, smears and employer pressure. Targets included King and the Panthers. Exposed by 1971 Media PA burglary and Church Committee. Ended 1971, led to DOJ guidelines limiting domestic intel.",
"chaos": "CIA domestic spying 1967-74 ordered by Johnson/Nixon to find foreign control of protests, despite charter ban. Angleton's staff compiled 7,000+ files, infiltrated groups, indexed dissidents. Rockefeller Commission found it improper and found no significant foreign control. Terminated 1974; spurred EO 11905, intel committees and FISA.",
"shamrock": "1945-1975 NSA/AFSA receipt of daily international telegrams from Western Union/RCA/ITT. Aimed at Soviets but swept up Americans without warrants. Voluntary corporate cooperation, kept secret. Church Committee called it likely illegal, largest interception of its era. Ended 1975; directly led to 1978 FISA warrant requirements.",
"minaret": "NSA watchlist 1967-73 intercepting international communications of King, Ali, Sen. Church, journalists and organizers at FBI/CIA/Army request. Disseminated to agencies, violating foreign-only mandate. Church Committee called it improper/illegal. Shut 1973; helped prompt FISA and AG guidelines.",
"mockingbird": "Imprecise name from a 1963 wiretap reference, not a formal project title. Documented fact: CIA kept 50+ paid journalist relationships and subsidized outlets (RFE, Encounter) to plant anti-communist propaganda, confirmed by Church Committee. Colby acknowledged; 1976 rules limited paid use of US journalists. Claims of total media control are unproven — distinguish proven contacts from contested scope.",
"phoenix": "1965-72 US-South Vietnamese campaign to neutralize Viet Cong infrastructure via DIOCC intel centers for capture/defection/killing. 26,000-41,000 neutralized, 20,000+ killed. Defended as targeted intel work; 1970-71 hearings documented torture, quotas and PRU killings. Ended with US withdrawal; key counterinsurgency-ethics case.",
"ranch-hand": "USAF 1962-71 spraying of 70M+ liters herbicides (45M liters Agent Orange with dioxin) via 19,000 C-123 missions to strip cover and crops. Millions exposed. VA presumes cancers/diabetes/birth-defect links; USAID remediated Da Nang/Bien Hoa. Scale confirmed by USAF histories. Chemical-weapons legality debated, health damage acknowledged.",
"popeye": "Secret 1967-72 cloud-seeding (silver/lead iodide, 2,600+ sorties) to extend monsoon and mire Ho Chi Minh Trail. Modest tactical effect, huge political impact after 1971 leak and 1974 hearings. Prompted 1978 UN ENMOD ban. Best-documented weather warfare.",
"shad-112": "DoD 1962-73 vulnerability tests: VX, sarin, E. coli, Q-fever released on ships and at Hawaii/Alaska/Marshall sites. ~6,000 servicemembers, many unwitting. Classified until 2000-03 veteran pressure. VA recognized exposures, offered exams/benefits. Central to consent and notification reforms."
};
