const EXTRA_D = {
"jtrig": "Snowden 2013-14 GCHQ slides (Intercept/NBC 2014) describe Joint Threat Research Intelligence Group online effects with Five Eyes: false personas, honeypots, DDoS, discrediting and poll manipulation against terrorists, hackers and criminals. GCHQ neither confirmed specifics nor denied program, defending lawful work under oversight. Sparked bulk-surveillance and 2016 Investigatory Powers Act debates.",
"porton-down": "Porton establishment 1940s-80s: 20,000+ servicemen exposed to sarin, VX, mustard and LSD with limited risk disclosure. 1953 airman Ronald Maddison died after sarin on arm; 2004 inquest ruled unlawful killing. MoD settled 360 claims (£3M, 2008), acknowledged Dorset germ releases. Central to consent and compensation debates.",
"embarrass": "MI6 1948 sabotage of five ships in Italian ports to block refugees/arms to Palestine and preserve mandate policy, via limpet mines, no acknowledged fatalities. Revealed via declassified files and Jeffery's official MI6 history (2010). Documented peacetime sabotage of civilian vessels.",
"rainbow-warrior": "DGSE bombing 10 July 1985 in Auckland to stop Moruroa protests: two mines sank Rainbow Warrior, drowning photographer Pereira. France denied then admitted; Mafart/Prieur convicted in NZ; defence minister resigned. UN arbitration: $7M to NZ, $8M+ to Greenpeace. Rare admitted state sabotage killing.",
"algiers-torture": "1954-62 French system under Massu, especially 1957 Algiers: electroshock, waterboarding, disappearances and executions of thousands. Alleg's La Question (1958) exposed it. Macron 2018 declared torture systematic and admitted murder of Audin, with declassification and memorials — core to French colonial reckoning.",
"barracuda": "Sept 1979 French paratroopers/DGSE deposed Bokassa during Libya trip after Ngaragba schoolchildren massacre and diamonds affair, restoring Dacko and securing Bangui. Acknowledged as ending abuses; critics call it neocolonial to keep bases/uranium. Textbook direct African intervention.",
"francafrique-chad": "Post-independence system of defence/currency/intel ties and Elysée Africa cell for oil, uranium and bases. Chad: Manta (1983), Épervier (1986+) troops/airpower vs Libya-backed forces backing Habré then Déby; similar backing in Gabon/Cameroon. Parliamentary probes and scholarship document covert funding; defenders cite invited stability help. Pattern proven, specific corruption debated.",
"gal-spain": "Interior-funded 1983-87 mercenary/police campaign vs ETA in France: kidnappings, bombings, shootings, 27 dead including uninvolved. Press exposed reserved-funds financing. Supreme Court 1998 convicted minister Barrionuevo, Vera and others for kidnapping/misuse. Spain's proven democratic-era state terrorism; prompted oversight reforms.",
"echelon": "Cold War Five Eyes satellite/cable network (NSA, GCHQ, CSE, ASD, GCSB) for Soviet then global interception. Exposed by Campbell 1988, EU STOA 1997-2001 warning of European interception. Governments admitted sharing, denied systematic industrial espionage; EU found capacity but limited proof. Shaped privacy, encryption and later PRISM debates.",
"prism-upstream": "Post-9/11 Section 702: PRISM via compelled tech-company cooperation, Upstream via backbone taps (NSA/FBI/GCHQ) for foreign intel. Snowden 2013 disclosures, FISA releases, PCLOB reviews. Firms denied direct access. Bulk telephony later ruled illegal; 2015 Freedom Act added transparency. 702 remains contested.",
"stellar-wind": "Bush-authorized post-9/11 warrantless NSA metadata/email collection. DOJ questioned legality — 2004 Ashcroft hospital standoff. NYT revealed 2005; parts brought under FISA 2007. IG reports and 2015 appeals ruling found bulk telephony illegal. Replaced by Freedom Act targeting — landmark reform precedent.",
"allan-memorial": "CIA Subproject 68 (1957-64): Cameron's depatterning/psychic driving at Montreal's Allan Memorial — massive electroshock, drug sleep, LSD, deprivation and taped messages, leaving amnesia. Patients sought depression care, not brainwashing tests. Exposed 1970s-80s; CIA settled 9 cases 1988, Canada paid 250+ patients. Core medical-ethics warning.",
"suez-sevres": "Oct 1956 secret pact (Eden/Mollet/Ben-Gurion): Israel invades Sinai as pretext for Anglo-French Suez seizure after nationalization, intel-coordinated. Denied then confirmed by archives/m memoirs 1980s+. Collapsed under US-Soviet pressure; Eden resigned. Symbol of imperial overreach.",
"strategy-tension": "1969-80 Italy bombings (Piazza Fontana 1969, Bologna 1980, dozens dead). Courts convicted Ordine Nuovo neo-fascists and NAR militants; Massacres Commissions found infiltration and obstruction. Journalists alleged Gladio/US masterminding, but no court proved it. Bombings proven; state-mastermind claim disputed/unproven."
};
