const EXTRA_A = {
"mkultra": "Authorized in 1953 by CIA Director Allen Dulles amid fears the USSR had mastered brainwashing, MKUltra was led by chemist Sidney Gottlieb to develop mind-control and interrogation techniques. It encompassed 149 subprojects at 44 universities, hospitals and prisons, testing LSD, hypnosis, sensory deprivation and sexual blackmail, often on unwitting subjects. Army scientist Frank Olson died in 1953 after covert LSD dosing. Director Helms ordered files destroyed in 1973. Exposed by the Church Committee and 1977 Senate hearings, it produced no usable weapon but forced oversight reforms and settlements.",
"midnight-climax": "An MKUltra subproject run by Sidney Gottlieb and narcotics officer George Hunter White (1954-1964). CIA safehouses in San Francisco and New York used paid sex workers to lure men who were secretly dosed with LSD and observed through two-way mirrors. Aim was to test drugs plus sex for interrogation and compromise. A 1963 IG report criticized poor supervision. Exposed by the Church Committee, it was closed in 1964-65 and became a central example of unwitting experimentation.",
"artichoke": "Authorized 1951 as successor to BLUEBIRD to answer Korean-War brainwashing fears. Goal: force confessions, create amnesia, or induce unwitting assassination via drugs, hypnosis and pressure. Tested morphine addiction/withdrawal, LSD, mescaline and hypnosis on prisoners and suspected double agents. Declassified memos confirm discussion of unwitting testing. Folded into MKUltra in 1953. Revealed in 1970s inquiries; yielded no reliable technique.",
"bluebird": "Authorized 1950 by CIA Director Walter Bedell Smith as the first postwar mind-control program. Offensive and defensive aims: develop interrogation drugs and protect US personnel. Tested hypnosis, sodium amytal/pentothal for amnesia and resistance. 1950-51 memos approve unwitting tests in some cases. Renamed ARTICHOKE in 1951, foundation for MKUltra. Exposed via declassifications and Church inquiries.",
"mknaomi": "Joint CIA-Army program (1950s-1970) under Sidney Gottlieb to give CIA lethal/incapacitating biological-chemical capability. Stockpiled ricin, shellfish toxin, dart guns and dissemination devices; studied crop/animal sabotage. Church Committee exposed retention of toxins despite Nixon's 1969 renunciation and 1970 destruction order. Director Colby disclosed the cache; materials destroyed, controls tightened.",
"paperclip": "1945-1959 program bringing 1,600+ German scientists (notably von Braun's rocket team) to the US to deny them to the USSR and accelerate rocketry and medicine. JIOA sanitized dossiers to bypass Truman's Nazi exclusion. Confirmed by National Archives. Technologically successful but a deliberate moral compromise shaping NASA and Cold War weapons work.",
"ajax-boot": "1953 US-UK operation to overthrow Iran's Mossadegh after oil nationalization. Planned by CIA's Kermit Roosevelt with MI6: bribery, propaganda, staged protests, persuading the Shah to dismiss Mossadegh. After initial failure, August 1953 push restored the Shah. CIA Wilber history declassified 2013 confirms planning. Entrenched authoritarian rule and fueled 1979 blowback.",
"pbsuccess": "CIA operation (1954) to topple Guatemala's Arbenz over land reform and UFCO interests, framed as anti-communism. Used Voice of Liberation radio, leaflets, CIA-flown bombings and Castillo Armas's 480-man force plus assassination lists. Arbenz resigned after army withdrew. Declassified histories confirm planning. Followed by decades of military rule and ~200,000 dead in civil war.",
"washtub": "1954 CIA propaganda cache supporting PBSUCCESS: Soviet-made arms planted near Nicaragua to be 'discovered' as proof of Moscow control of Guatemala. Displayed to press and officials. Later histories acknowledge staging. Cited as documented false-cache propaganda; did not prove Soviet control, generally seen as limited.",
"mongoose": "Authorized late 1961 after Bay of Pigs to weaken Castro. Run by Lansdale's Special Group with RFK interest: sabotage of sugar/infrastructure, raids, propaganda, plus CIA-Mafia assassination plotting documented in 1967 IG report. Hundreds of ops failed to topple Castro, deepened US-Cuba hostility before the 1962 Missile Crisis.",
"northwoods": "Proposed 13 March 1962 JCS memo (Lemnitzer) for staged hijackings, bombings, drone airliner shoot-down and fake casualties to justify invading Cuba. Rejected by Kennedy, who replaced Lemnitzer. Declassified 1997-98 via JFK Review Board (NARA). Genuine rejected proposal, not executed — often misrepresented online.",
"fubelt": "Nixon-authorized 1970 CIA program to block Allende then destabilize Chile: Track I parliamentary maneuvering, Track II coup promotion. Funded opposition, El Mercurio, strikes and propaganda; contacts linked to Gen. Schneider's 1970 killing. Hinchey Report (2000) confirms destabilization but no US order for murder. Ended with 1973 Pinochet coup."
};
